version: '2'

services:
  site:
    image: exira/your-site

  nginx:
    image: exira/nginx:1.11.3
    restart: always
    ports:
     - 80
     - 443
    depends_on:
     - site
    volumes_from:
     - site:
    environment:
      VIRTUAL_HOST: 'example.org'
