version: '2'

services:
  site:
    build: .

  nginx:
    image: exira/nginx:1.11.3
    restart: always
    ports:
     - 80:80
     - 443:443
    depends_on:
     - site
    volumes_from:
     - site:
    environment:
      VIRTUAL_HOST: 'example.org'

networks:
  default:
    external:
      name: static-sites
